# Generated by Django 5.2.3 on 2025-06-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='课程代码')),
                ('title', models.CharField(max_length=200, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程描述')),
                ('credits', models.PositiveIntegerField(verbose_name='学分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
