# Generated by Django 5.2.3 on 2025-12-14 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='教师编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('title', models.CharField(max_length=50, verbose_name='职称')),
                ('department', models.CharField(max_length=100, verbose_name='所属部门')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('office', models.CharField(blank=True, max_length=100, null=True, verbose_name='办公室')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('required', '必修课'), ('elective', '选修课')], default='required', max_length=20, verbose_name='课程类型'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=60, verbose_name='最大选课人数'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='2024-2025-1', max_length=20, verbose_name='开课学期'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', '周一'), ('tuesday', '周二'), ('wednesday', '周三'), ('thursday', '周四'), ('friday', '周五'), ('saturday', '周六'), ('sunday', '周日')], max_length=10, verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('classroom', models.CharField(max_length=50, verbose_name='教室')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '排课信息',
                'verbose_name_plural': '排课信息',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.teacher', verbose_name='任课教师'),
        ),
    ]
