# Generated by Django 5.2.3 on 2025-12-14 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_teacher_course_course_type_course_max_students_and_more'),
        ('students', '0002_alter_student_options_student_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('2024-2025-1', '2024-2025学年第一学期'), ('2024-2025-2', '2024-2025学年第二学期'), ('2025-2026-1', '2025-2026学年第一学期'), ('2025-2026-2', '2025-2026学年第二学期')], default='2024-2025-1', max_length=15, verbose_name='学期')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('status', models.CharField(choices=[('enrolled', '已选'), ('dropped', '已退课'), ('completed', '已完成'), ('in_progress', '进行中')], default='enrolled', max_length=15, verbose_name='选课状态')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
