# Generated by Django 5.2.3 on 2025-12-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_teacher_course_course_type_course_max_students_and_more'),
        ('students', '0002_alter_student_options_student_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('2024-2025-1', '2024-2025学年第一学期'), ('2024-2025-2', '2024-2025学年第二学期'), ('2025-2026-1', '2025-2026学年第一学期'), ('2025-2026-2', '2025-2026学年第二学期')], default='2024-2025-1', max_length=15, verbose_name='学期')),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期中考试成绩')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期末考试成绩')),
                ('attendance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='考勤成绩')),
                ('assignment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='作业成绩')),
                ('project_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='项目成绩')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='总评成绩')),
                ('grade_level', models.CharField(blank=True, max_length=2, null=True, verbose_name='等级')),
                ('comments', models.TextField(blank=True, verbose_name='教师评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩管理',
                'ordering': ['student', 'course', 'semester'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
