# Generated by Django 5.2.3 on 2026-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_video'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='video',
            name='unique_main_video_per_project',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='其他', max_length=100, verbose_name='视频分类'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='项目在 URL 中的唯一标识', null=True, unique=True, verbose_name='URL 别名'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('project', 'is_main')},
        ),
    ]
