# Generated by Django 5.2.3 on 2026-02-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_video_unique_main_video_per_project_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
    ]
