"""
Django settings for profile_website project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 安全密钥：在生产环境中应保持保密
SECRET_KEY = 'django-insecure-7fp=9!pdyvtyb6nc##d-(l5*u7%903s%jhsv96p0vehswx7p4g'

# 调试模式：在生产环境中应设置为False
DEBUG = True

# 允许的主机：指定哪些主机名/IP可以访问该网站
ALLOWED_HOSTS = ['enzibio.cloud', 'www.enzibio.cloud', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',        # Django管理后台
    'django.contrib.auth',          # 认证系统
    'django.contrib.contenttypes',  # 内容类型框架
    'django.contrib.sessions',      # 会话管理
    'django.contrib.messages',      # 消息框架
    'django.contrib.staticfiles',   # 静态文件管理
    'portfolio',                    # 自定义的作品集应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # 安全中间件
    'django.contrib.sessions.middleware.SessionMiddleware',  # 会话中间件
    'django.middleware.locale.LocaleMiddleware',  # 语言切换中间件
    'django.middleware.common.CommonMiddleware',  # 通用中间件
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF保护中间件
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 认证中间件
    'django.contrib.messages.middleware.MessageMiddleware',  # 消息中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 点击劫持保护中间件
]

# 根URL配置
ROOT_URLCONF = 'profile_website.urls'

# 模板配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 模板后端
        'DIRS': [],  # 模板目录
        'APP_DIRS': True,  # 是否在应用目录中查找模板
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # 请求上下文处理器
                'django.template.context_processors.media',  # 媒体文件上下文处理器
                'django.contrib.auth.context_processors.auth',  # 认证上下文处理器
                'django.contrib.messages.context_processors.messages',  # 消息上下文处理器
            ],
        },
    },
]

# WSGI应用
WSGI_APPLICATION = 'profile_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # 数据库引擎
        'NAME': BASE_DIR / 'db.sqlite3',  # 数据库名称
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # 用户名相似性验证
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # 最小长度验证
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # 常见密码验证
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # 纯数字密码验证
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

# 默认语言
LANGUAGE_CODE = 'en'

# 支持的语言列表
LANGUAGES = [
    ('zh-CN', _('中文')),
    ('en', _('English')),
]

# 时区
TIME_ZONE = 'UTC'

# 是否使用国际化
USE_I18N = True

# 是否使用本地化
USE_L10N = True

# 是否使用时区
USE_TZ = True

# 语言文件存放路径
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  # 静态文件URL前缀
STATICFILES_DIRS = []  # 静态文件目录列表
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 静态文件收集目录

# Media files (Uploaded images)
MEDIA_URL = 'media/'  # 媒体文件URL前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 媒体文件存储目录

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # 默认主键字段类型
