# Generated by Django 5.2.3 on 2025-12-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': '学生', 'verbose_name_plural': '学生管理'},
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='未分配', max_length=50, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(default='', max_length=100, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(default='', max_length=20, verbose_name='紧急联系电话'),
        ),
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(default='汉族', max_length=50, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='student',
            name='political_status',
            field=models.CharField(choices=[('party_member', '党员'), ('probationary_member', '预备党员'), ('league_member', '团员'), ('mass', '群众')], default='mass', max_length=20, verbose_name='政治面貌'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enrolled', '在读'), ('suspended', '休学'), ('graduated', '毕业'), ('dropped', '退学')], default='enrolled', max_length=20, verbose_name='学籍状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(verbose_name='入学日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=100, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
