# Generated by Django 5.2.3 on 2025-12-14 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(max_length=200, verbose_name='职位')),
                ('bio', models.TextField(verbose_name='个人简介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('website', models.URLField(blank=True, null=True, verbose_name='个人网站')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('category', models.CharField(max_length=100, verbose_name='项目类别')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='项目图片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='项目链接')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub链接')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作品集',
                'verbose_name_plural': '作品集',
                'ordering': ['-created_at'],
            },
        ),
    ]
