# Generated by Django 5.2.3 on 2025-12-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_personalinfo_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='meta',
            field=models.URLField(blank=True, null=True, verbose_name='Meta/Facebook'),
        ),
    ]
