# Generated by Django 5.2.3 on 2025-12-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_personalinfo_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='short_bio',
            field=models.TextField(blank=True, null=True, verbose_name='简短简介'),
        ),
    ]
