# Generated by Django 5.2.3 on 2025-12-15 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_personalinfo_short_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='证书名称')),
                ('issuing_authority', models.CharField(max_length=200, verbose_name='颁发机构')),
                ('issue_date', models.DateField(verbose_name='颁发日期')),
                ('certificate_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='证书编号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='证书描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='证书图片')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
                'ordering': ['-issue_date'],
            },
        ),
    ]
